In [1]:
import Metashape
import pandas as pd
import numpy as np

import configs as cfg
import os

In [2]:
ms_list = ['1R_Group0', '1R_Group1', '1R_Group2', 
           '2R_Group0',
           '3R_Group0', '3R_Group1',
           '4R_Group0', '4R_Group1',
           '5R_Group0', 
           'XR_GroupFix']

In [3]:
vol_dict = {}
area_dict = {}

for ms_name in ms_list:
    doc = Metashape.Document()
    doc.open(os.path.join(cfg.working_directory, "projects.psx", ms_name + '.psx'))

    for chunk in doc.chunks:
        vol_dict[chunk.label] = chunk.model.volume()
        area_dict[chunk.label] = chunk.model.area()

LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/1R_Group0.psx
loaded project in 0.112643 sec
loaded mesh in 0.029832 sec
loaded mesh in 0.008961 sec
loaded mesh in 0.032434 sec
loaded mesh in 0.00796 sec
loaded mesh in 0.035232 sec
loaded mesh in 0.015513 sec
loaded mesh in 0.03265 sec
loaded mesh in 0.01338 sec
loaded mesh in 0.03022 sec
loaded mesh in 0.009231 sec
loaded mesh in 0.028283 sec
loaded mesh in 0.004525 sec
loaded mesh in 0.039035 sec
loaded mesh in 0.013152 sec
loaded mesh in 0.025619 sec
loaded mesh in 0.008726 sec
loaded mesh in 0.048884 sec
loaded mesh in 0.018907 sec
loaded mesh in 0.035592 sec
loaded mesh in 0.010708 sec
loaded mesh in 0.031966 sec
loaded mesh in 0.00986 sec
loaded mesh in 0.024508 sec
loaded mesh in 0.008696 sec
loaded mesh in 0.042255 sec
loaded mesh in 0.016309 sec
loaded mesh in 0.028233 sec
loaded mesh in 0.006014 sec
loaded mesh in 0.035384 sec
loaded mesh in 0.015039 sec
loaded mesh in 0.048932 sec
loaded mesh in 0.021217 sec
loaded mesh in 0.049235 sec
loaded mesh in 0.018532 sec
loaded mesh in 0.024785 sec
loaded mesh in 0.010542 sec
loaded mesh in 0.029028 sec
loaded mesh in 0.012806 sec
loaded mesh in 0.029865 sec
loaded mesh in 0.009265 sec
loaded mesh in 0.03073 sec
loaded mesh in 0.0098 sec
loaded mesh in 0.026139 sec
loaded mesh in 0.008412 sec
loaded mesh in 0.026061 sec
loaded mesh in 0.01086 sec
loaded mesh in 0.027247 sec
loaded mesh in 0.010446 sec
loaded mesh in 0.042924 sec
loaded mesh in 0.015249 sec
loaded mesh in 0.027666 sec
loaded mesh in 0.013728 sec
loaded mesh in 0.04247 sec
loaded mesh in 0.009244 sec
loaded mesh in 0.052595 sec
loaded mesh in 0.024511 sec
loaded mesh in 0.032763 sec
loaded mesh in 0.009417 sec
loaded mesh in 0.031904 sec
loaded mesh in 0.01083 sec
loaded mesh in 0.045837 sec
loaded mesh in 0.016939 sec
loaded mesh in 0.024989 sec
loaded mesh in 0.008171 sec
loaded mesh in 0.041879 sec
loaded mesh in 0.017159 sec
loaded mesh in 0.045786 sec
loaded mesh in 0.015237 sec
loaded mesh in 0.027585 sec
loaded mesh in 0.005952 sec
loaded mesh in 0.036507 sec
loaded mesh in 0.013632 sec
loaded mesh in 0.030312 sec
loaded mesh in 0.008198 sec
loaded mesh in 0.029004 sec
loaded mesh in 0.012337 sec
loaded mesh in 0.028795 sec
loaded mesh in 0.010861 sec
loaded mesh in 0.032368 sec
loaded mesh in 0.011166 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/1R_Group1.psx
loaded project in 0.049488 sec
loaded mesh in 0.035746 sec
loaded mesh in 0.010192 sec
loaded mesh in 0.03809 sec
loaded mesh in 0.013519 sec
loaded mesh in 0.04808 sec
loaded mesh in 0.017494 sec
loaded mesh in 0.051196 sec
loaded mesh in 0.017315 sec
loaded mesh in 0.024352 sec
loaded mesh in 0.005931 sec
loaded mesh in 0.023307 sec
loaded mesh in 0.006182 sec
loaded mesh in 0.029302 sec
loaded mesh in 0.011205 sec
loaded mesh in 0.025677 sec
loaded mesh in 0.009251 sec
loaded mesh in 0.038028 sec
loaded mesh in 0.01127 sec
loaded mesh in 0.042915 sec
loaded mesh in 0.012583 sec
loaded mesh in 0.034352 sec
loaded mesh in 0.011497 sec
loaded mesh in 0.015211 sec
loaded mesh in 0.007982 sec
loaded mesh in 0.031487 sec
loaded mesh in 0.011027 sec
loaded mesh in 0.013318 sec
loaded mesh in 0.006362 sec
loaded mesh in 0.049268 sec
loaded mesh in 0.017495 sec
loaded mesh in 0.049371 sec
loaded mesh in 0.014921 sec
loaded mesh in 0.036116 sec
loaded mesh in 0.009971 sec
loaded mesh in 0.030406 sec
loaded mesh in 0.008088 sec
loaded mesh in 0.044313 sec
loaded mesh in 0.01148 sec
loaded mesh in 0.034344 sec
loaded mesh in 0.009306 sec
loaded mesh in 0.053999 sec
loaded mesh in 0.016501 sec
loaded mesh in 0.034575 sec
loaded mesh in 0.009204 sec
loaded mesh in 0.033832 sec
loaded mesh in 0.010577 sec
loaded mesh in 0.050285 sec
loaded mesh in 0.01743 sec
loaded mesh in 0.050475 sec
loaded mesh in 0.01642 sec
loaded mesh in 0.026822 sec
loaded mesh in 0.00453 sec
loaded mesh in 0.04919 sec
loaded mesh in 0.01648 sec
loaded mesh in 0.05136 sec
loaded mesh in 0.014871 sec
loaded mesh in 0.027907 sec
loaded mesh in 0.008253 sec
loaded mesh in 0.063846 sec
loaded mesh in 0.021444 sec
loaded mesh in 0.030546 sec
loaded mesh in 0.009154 sec
loaded mesh in 0.045324 sec
loaded mesh in 0.011941 sec
loaded mesh in 0.033338 sec
loaded mesh in 0.009159 sec
loaded mesh in 0.057216 sec
loaded mesh in 0.020555 sec
loaded mesh in 0.031692 sec
loaded mesh in 0.009108 sec
loaded mesh in 0.059578 sec
loaded mesh in 0.021507 sec
loaded mesh in 0.052236 sec
loaded mesh in 0.019818 sec
loaded mesh in 0.027059 sec
loaded mesh in 0.00777 sec
loaded mesh in 0.035412 sec
loaded mesh in 0.012851 sec
loaded mesh in 0.031438 sec
loaded mesh in 0.008501 sec
loaded mesh in 0.040826 sec
loaded mesh in 0.011993 sec
loaded mesh in 0.014913 sec
loaded mesh in 0.007601 sec
loaded mesh in 0.017565 sec
loaded mesh in 0.007259 sec
loaded mesh in 0.03539 sec
loaded mesh in 0.01332 sec
loaded mesh in 0.014639 sec
loaded mesh in 0.007521 sec
loaded mesh in 0.059058 sec
loaded mesh in 0.017317 sec
loaded mesh in 0.022767 sec
loaded mesh in 0.010207 sec
loaded mesh in 0.031198 sec
loaded mesh in 0.011405 sec
loaded mesh in 0.015783 sec
loaded mesh in 0.008591 sec
loaded mesh in 0.056322 sec
loaded mesh in 0.009996 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/1R_Group2.psx
loaded project in 0.037351 sec
loaded mesh in 0.047594 sec
loaded mesh in 0.014815 sec
loaded mesh in 0.029458 sec
loaded mesh in 0.00935 sec
loaded mesh in 0.054833 sec
loaded mesh in 0.017832 sec
loaded mesh in 0.034059 sec
loaded mesh in 0.010891 sec
loaded mesh in 0.034197 sec
loaded mesh in 0.01051 sec
loaded mesh in 0.038591 sec
loaded mesh in 0.014128 sec
loaded mesh in 0.039395 sec
loaded mesh in 0.012665 sec
loaded mesh in 0.05231 sec
loaded mesh in 0.021869 sec
loaded mesh in 0.033388 sec
loaded mesh in 0.00611 sec
loaded mesh in 0.051847 sec
loaded mesh in 0.016101 sec
loaded mesh in 0.049429 sec
loaded mesh in 0.018855 sec
loaded mesh in 0.033642 sec
loaded mesh in 0.011696 sec
loaded mesh in 0.025551 sec
loaded mesh in 0.006102 sec
loaded mesh in 0.03151 sec
loaded mesh in 0.009632 sec
loaded mesh in 0.036298 sec
loaded mesh in 0.011468 sec
loaded mesh in 0.051253 sec
loaded mesh in 0.021403 sec
loaded mesh in 0.052957 sec
loaded mesh in 0.019315 sec
loaded mesh in 0.052261 sec
loaded mesh in 0.017737 sec
loaded mesh in 0.034705 sec
loaded mesh in 0.010107 sec
loaded mesh in 0.0311 sec
loaded mesh in 0.009939 sec
loaded mesh in 0.051417 sec
loaded mesh in 0.017735 sec
loaded mesh in 0.032321 sec
loaded mesh in 0.008447 sec
loaded mesh in 0.034359 sec
loaded mesh in 0.009012 sec
loaded mesh in 0.051594 sec
loaded mesh in 0.019952 sec
loaded mesh in 0.035324 sec
loaded mesh in 0.015279 sec
loaded mesh in 0.04945 sec
loaded mesh in 0.019874 sec
loaded mesh in 0.059037 sec
loaded mesh in 0.022399 sec
loaded mesh in 0.048311 sec
loaded mesh in 0.01642 sec
loaded mesh in 0.0598 sec
loaded mesh in 0.026224 sec
loaded mesh in 0.049768 sec
loaded mesh in 0.020002 sec
loaded mesh in 0.030684 sec
loaded mesh in 0.009563 sec
loaded mesh in 0.054919 sec
loaded mesh in 0.017785 sec
loaded mesh in 0.049132 sec
loaded mesh in 0.017994 sec
loaded mesh in 0.053349 sec
loaded mesh in 0.020672 sec
loaded mesh in 0.049737 sec
loaded mesh in 0.015717 sec
loaded mesh in 0.044868 sec
loaded mesh in 0.015007 sec
loaded mesh in 0.034954 sec
loaded mesh in 0.009561 sec
loaded mesh in 0.036133 sec
loaded mesh in 0.013962 sec
loaded mesh in 0.05355 sec
loaded mesh in 0.023392 sec
loaded mesh in 0.077169 sec
loaded mesh in 0.020566 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/2R_Group0.psx
loaded project in 0.030317 sec
loaded mesh in 0.045788 sec
loaded mesh in 0.02108 sec
loaded mesh in 0.050667 sec
loaded mesh in 0.020886 sec
loaded mesh in 0.026814 sec
loaded mesh in 0.011316 sec
loaded mesh in 0.049583 sec
loaded mesh in 0.018454 sec
loaded mesh in 0.034751 sec
loaded mesh in 0.010486 sec
loaded mesh in 0.052617 sec
loaded mesh in 0.018199 sec
loaded mesh in 0.049715 sec
loaded mesh in 0.016723 sec
loaded mesh in 0.031661 sec
loaded mesh in 0.009727 sec
loaded mesh in 0.035444 sec
loaded mesh in 0.009109 sec
loaded mesh in 0.032441 sec
loaded mesh in 0.010728 sec
loaded mesh in 0.033637 sec
loaded mesh in 0.010267 sec
loaded mesh in 0.046831 sec
loaded mesh in 0.020425 sec
loaded mesh in 0.031725 sec
loaded mesh in 0.011731 sec
loaded mesh in 0.037366 sec
loaded mesh in 0.013025 sec
loaded mesh in 0.038437 sec
loaded mesh in 0.011267 sec
loaded mesh in 0.035573 sec
loaded mesh in 0.011858 sec
loaded mesh in 0.034336 sec
loaded mesh in 0.010683 sec
loaded mesh in 0.035161 sec
loaded mesh in 0.010323 sec
loaded mesh in 0.038581 sec
loaded mesh in 0.014356 sec
loaded mesh in 0.031254 sec
loaded mesh in 0.009518 sec
loaded mesh in 0.035298 sec
loaded mesh in 0.013577 sec
loaded mesh in 0.037048 sec
loaded mesh in 0.01088 sec
loaded mesh in 0.050931 sec
loaded mesh in 0.019242 sec
loaded mesh in 0.036233 sec
loaded mesh in 0.013581 sec
loaded mesh in 0.050033 sec
loaded mesh in 0.017512 sec
loaded mesh in 0.031063 sec
loaded mesh in 0.010515 sec
loaded mesh in 0.038291 sec
loaded mesh in 0.011725 sec
loaded mesh in 0.035582 sec
loaded mesh in 0.012288 sec
loaded mesh in 0.053418 sec
loaded mesh in 0.018881 sec
loaded mesh in 0.050324 sec
loaded mesh in 0.020159 sec
loaded mesh in 0.053035 sec
loaded mesh in 0.018872 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/3R_Group0.psx
loaded project in 0.037899 sec
loaded mesh in 0.036614 sec
loaded mesh in 0.01314 sec
loaded mesh in 0.03041 sec
loaded mesh in 0.008831 sec
loaded mesh in 0.02868 sec
loaded mesh in 0.012066 sec
loaded mesh in 0.045611 sec
loaded mesh in 0.018389 sec
loaded mesh in 0.03172 sec
loaded mesh in 0.008678 sec
loaded mesh in 0.030782 sec
loaded mesh in 0.008499 sec
loaded mesh in 0.033415 sec
loaded mesh in 0.011751 sec
loaded mesh in 0.051067 sec
loaded mesh in 0.019536 sec
loaded mesh in 0.03436 sec
loaded mesh in 0.013415 sec
loaded mesh in 0.04683 sec
loaded mesh in 0.020678 sec
loaded mesh in 0.047928 sec
loaded mesh in 0.018797 sec
loaded mesh in 0.047301 sec
loaded mesh in 0.021222 sec
loaded mesh in 0.050595 sec
loaded mesh in 0.021577 sec
loaded mesh in 0.048367 sec
loaded mesh in 0.022356 sec
loaded mesh in 0.042674 sec
loaded mesh in 0.017239 sec
loaded mesh in 0.046871 sec
loaded mesh in 0.013813 sec
loaded mesh in 0.054637 sec
loaded mesh in 0.022403 sec
loaded mesh in 0.048399 sec
loaded mesh in 0.014402 sec
loaded mesh in 0.03659 sec
loaded mesh in 0.009341 sec
loaded mesh in 0.030974 sec
loaded mesh in 0.009992 sec
loaded mesh in 0.052226 sec
loaded mesh in 0.024096 sec
loaded mesh in 0.034388 sec
loaded mesh in 0.009651 sec
loaded mesh in 0.053087 sec
loaded mesh in 0.025225 sec
loaded mesh in 0.035001 sec
loaded mesh in 0.011443 sec
loaded mesh in 0.026439 sec
loaded mesh in 0.008192 sec
loaded mesh in 0.057978 sec
loaded mesh in 0.020731 sec
loaded mesh in 0.048073 sec
loaded mesh in 0.017418 sec
loaded mesh in 0.053932 sec
loaded mesh in 0.019837 sec
loaded mesh in 0.050316 sec
loaded mesh in 0.018053 sec
loaded mesh in 0.050146 sec
loaded mesh in 0.021505 sec
loaded mesh in 0.060862 sec
loaded mesh in 0.026617 sec
loaded mesh in 0.035583 sec
loaded mesh in 0.010656 sec
loaded mesh in 0.052479 sec
loaded mesh in 0.022423 sec
loaded mesh in 0.048416 sec
loaded mesh in 0.017525 sec
loaded mesh in 0.044619 sec
loaded mesh in 0.01746 sec
loaded mesh in 0.045424 sec
loaded mesh in 0.014123 sec
loaded mesh in 0.025327 sec
loaded mesh in 0.00733 sec
loaded mesh in 0.042687 sec
loaded mesh in 0.014527 sec
loaded mesh in 0.030327 sec
loaded mesh in 0.011914 sec
loaded mesh in 0.024029 sec
loaded mesh in 0.005972 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/3R_Group1.psx
loaded project in 0.029917 sec
loaded mesh in 0.052907 sec
loaded mesh in 0.023941 sec
loaded mesh in 0.033565 sec
loaded mesh in 0.00814 sec
loaded mesh in 0.05421 sec
loaded mesh in 0.022033 sec
loaded mesh in 0.048482 sec
loaded mesh in 0.014467 sec
loaded mesh in 0.036369 sec
loaded mesh in 0.013224 sec
loaded mesh in 0.049991 sec
loaded mesh in 0.017743 sec
loaded mesh in 0.030493 sec
loaded mesh in 0.00742 sec
loaded mesh in 0.035861 sec
loaded mesh in 0.011372 sec
loaded mesh in 0.050084 sec
loaded mesh in 0.018215 sec
loaded mesh in 0.031233 sec
loaded mesh in 0.011016 sec
loaded mesh in 0.04637 sec
loaded mesh in 0.011564 sec
loaded mesh in 0.035226 sec
loaded mesh in 0.012994 sec
loaded mesh in 0.047219 sec
loaded mesh in 0.018401 sec
loaded mesh in 0.045332 sec
loaded mesh in 0.013873 sec
loaded mesh in 0.044684 sec
loaded mesh in 0.0141 sec
loaded mesh in 0.052405 sec
loaded mesh in 0.022341 sec
loaded mesh in 0.049496 sec
loaded mesh in 0.021847 sec
loaded mesh in 0.054354 sec
loaded mesh in 0.021424 sec
loaded mesh in 0.054966 sec
loaded mesh in 0.021364 sec
loaded mesh in 0.054503 sec
loaded mesh in 0.020145 sec
loaded mesh in 0.05681 sec
loaded mesh in 0.024148 sec
loaded mesh in 0.02872 sec
loaded mesh in 0.00695 sec
loaded mesh in 0.056662 sec
loaded mesh in 0.017359 sec
loaded mesh in 0.05318 sec
loaded mesh in 0.021544 sec
loaded mesh in 0.03377 sec
loaded mesh in 0.008126 sec
loaded mesh in 0.038501 sec
loaded mesh in 0.013033 sec
loaded mesh in 0.04861 sec
loaded mesh in 0.018181 sec
loaded mesh in 0.028148 sec
loaded mesh in 0.00798 sec
loaded mesh in 0.034001 sec
loaded mesh in 0.012883 sec
loaded mesh in 0.049925 sec
loaded mesh in 0.009914 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/4R_Group0.psx
loaded project in 0.037712 sec
loaded mesh in 0.044916 sec
loaded mesh in 0.01596 sec
loaded mesh in 0.030524 sec
loaded mesh in 0.013427 sec
loaded mesh in 0.034582 sec
loaded mesh in 0.01045 sec
loaded mesh in 0.03811 sec
loaded mesh in 0.014128 sec
loaded mesh in 0.032927 sec
loaded mesh in 0.011645 sec
loaded mesh in 0.028165 sec
loaded mesh in 0.009676 sec
loaded mesh in 0.042048 sec
loaded mesh in 0.015283 sec
loaded mesh in 0.029522 sec
loaded mesh in 0.006891 sec
loaded mesh in 0.049497 sec
loaded mesh in 0.015673 sec
loaded mesh in 0.050308 sec
loaded mesh in 0.019115 sec
loaded mesh in 0.035135 sec
loaded mesh in 0.012391 sec
loaded mesh in 0.033886 sec
loaded mesh in 0.013561 sec
loaded mesh in 0.032834 sec
loaded mesh in 0.006841 sec
loaded mesh in 0.04812 sec
loaded mesh in 0.014525 sec
loaded mesh in 0.056854 sec
loaded mesh in 0.020532 sec
loaded mesh in 0.030721 sec
loaded mesh in 0.006648 sec
loaded mesh in 0.038867 sec
loaded mesh in 0.014196 sec
loaded mesh in 0.035888 sec
loaded mesh in 0.014812 sec
loaded mesh in 0.036535 sec
loaded mesh in 0.011918 sec
loaded mesh in 0.044004 sec
loaded mesh in 0.014514 sec
loaded mesh in 0.037099 sec
loaded mesh in 0.011224 sec
loaded mesh in 0.047678 sec
loaded mesh in 0.017372 sec
loaded mesh in 0.049859 sec
loaded mesh in 0.02034 sec
loaded mesh in 0.035157 sec
loaded mesh in 0.010792 sec
loaded mesh in 0.038957 sec
loaded mesh in 0.013928 sec
loaded mesh in 0.053049 sec
loaded mesh in 0.020276 sec
loaded mesh in 0.037817 sec
loaded mesh in 0.011952 sec
loaded mesh in 0.033868 sec
loaded mesh in 0.01208 sec
loaded mesh in 0.031847 sec
loaded mesh in 0.012483 sec
loaded mesh in 0.056938 sec
loaded mesh in 0.022263 sec
loaded mesh in 0.03453 sec
loaded mesh in 0.008424 sec
loaded mesh in 0.031586 sec
loaded mesh in 0.010733 sec
loaded mesh in 0.052341 sec
loaded mesh in 0.019295 sec
loaded mesh in 0.049779 sec
loaded mesh in 0.018173 sec
loaded mesh in 0.048592 sec
loaded mesh in 0.016549 sec
loaded mesh in 0.037219 sec
loaded mesh in 0.012107 sec
loaded mesh in 0.032259 sec
loaded mesh in 0.011657 sec
loaded mesh in 0.052484 sec
loaded mesh in 0.019823 sec
loaded mesh in 0.034688 sec
loaded mesh in 0.009053 sec
loaded mesh in 0.031246 sec
loaded mesh in 0.011123 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/4R_Group1.psx
loaded project in 0.042235 sec
loaded mesh in 0.035797 sec
loaded mesh in 0.015609 sec
loaded mesh in 0.053449 sec
loaded mesh in 0.019167 sec
loaded mesh in 0.046906 sec
loaded mesh in 0.014632 sec
loaded mesh in 0.030345 sec
loaded mesh in 0.009975 sec
loaded mesh in 0.043669 sec
loaded mesh in 0.016068 sec
loaded mesh in 0.045995 sec
loaded mesh in 0.013871 sec
loaded mesh in 0.030782 sec
loaded mesh in 0.008423 sec
loaded mesh in 0.034164 sec
loaded mesh in 0.011962 sec
loaded mesh in 0.03623 sec
loaded mesh in 0.012231 sec
loaded mesh in 0.028525 sec
loaded mesh in 0.006964 sec
loaded mesh in 0.046492 sec
loaded mesh in 0.015323 sec
loaded mesh in 0.035444 sec
loaded mesh in 0.010641 sec
loaded mesh in 0.033683 sec
loaded mesh in 0.013711 sec
loaded mesh in 0.027189 sec
loaded mesh in 0.005289 sec
loaded mesh in 0.030936 sec
loaded mesh in 0.007541 sec
loaded mesh in 0.049617 sec
loaded mesh in 0.015079 sec
loaded mesh in 0.046205 sec
loaded mesh in 0.015758 sec
loaded mesh in 0.057616 sec
loaded mesh in 0.028948 sec
loaded mesh in 0.04822 sec
loaded mesh in 0.015425 sec
loaded mesh in 0.034205 sec
loaded mesh in 0.0096 sec
loaded mesh in 0.050891 sec
loaded mesh in 0.016992 sec
loaded mesh in 0.028771 sec
loaded mesh in 0.007431 sec
loaded mesh in 0.037984 sec
loaded mesh in 0.013137 sec
loaded mesh in 0.041201 sec
loaded mesh in 0.018057 sec
loaded mesh in 0.029658 sec
loaded mesh in 0.00914 sec
loaded mesh in 0.037865 sec
loaded mesh in 0.012131 sec
loaded mesh in 0.031033 sec
loaded mesh in 0.011442 sec
loaded mesh in 0.050232 sec
loaded mesh in 0.014607 sec
loaded mesh in 0.048517 sec
loaded mesh in 0.017567 sec
loaded mesh in 0.045887 sec
loaded mesh in 0.018883 sec
loaded mesh in 0.049987 sec
loaded mesh in 0.01689 sec
loaded mesh in 0.032987 sec
loaded mesh in 0.010893 sec
loaded mesh in 0.033837 sec
loaded mesh in 0.015041 sec
loaded mesh in 0.035062 sec
loaded mesh in 0.013795 sec
loaded mesh in 0.036467 sec
loaded mesh in 0.013704 sec
loaded mesh in 0.049728 sec
loaded mesh in 0.017264 sec
loaded mesh in 0.035294 sec
loaded mesh in 0.014573 sec
loaded mesh in 0.045309 sec
loaded mesh in 0.014019 sec
loaded mesh in 0.048491 sec
loaded mesh in 0.023116 sec
loaded mesh in 0.033213 sec
loaded mesh in 0.007031 sec
LoadProject: path = /home/crest/w/hwang_Pro/data/2023_hokkaido_potato/projects.psx/5R_Group0.psx
loaded project in 0.040161 sec
loaded mesh in 0.038762 sec
loaded mesh in 0.011941 sec
loaded mesh in 0.034024 sec
loaded mesh in 0.012637 sec
loaded mesh in 0.031657 sec
loaded mesh in 0.008461 sec
loaded mesh in 0.049933 sec
loaded mesh in 0.01907 sec
loaded mesh in 0.055857 sec
loaded mesh in 0.023969 sec
loaded mesh in 0.023039 sec
loaded mesh in 0.007749 sec
loaded mesh in 0.027119 sec
loaded mesh in 0.011509 sec
loaded mesh in 0.025005 sec
loaded mesh in 0.012848 sec
loaded mesh in 0.031094 sec
loaded mesh in 0.007818 sec
loaded mesh in 0.050306 sec
loaded mesh in 0.016491 sec
loaded mesh in 0.030532 sec
loaded mesh in 0.012935 sec
loaded mesh in 0.027778 sec
loaded mesh in 0.00972 sec
loaded mesh in 0.024979 sec
loaded mesh in 0.006234 sec
loaded mesh in 0.021829 sec
loaded mesh in 0.009178 sec
loaded mesh in 0.03626 sec
loaded mesh in 0.013831 sec
loaded mesh in 0.026905 sec
loaded mesh in 0.008048 sec
loaded mesh in 0.036772 sec
loaded mesh in 0.012888 sec
loaded mesh in 0.015229 sec
loaded mesh in 0.00821 sec
loaded mesh in 0.043871 sec
loaded mesh in 0.016134 sec
loaded mesh in 0.037467 sec
loaded mesh in 0.01282 sec
loaded mesh in 0.03836 sec
loaded mesh in 0.007045 sec
loaded mesh in 0.033582 sec
loaded mesh in 0.010417 sec
loaded mesh in 0.047263 sec
loaded mesh in 0.018487 sec
loaded mesh in 0.043693 sec
loaded mesh in 0.014502 sec
loaded mesh in 0.02107 sec
loaded mesh in 0.007126 sec
loaded mesh in 0.023929 sec
loaded mesh in 0.009554 sec
loaded mesh in 0.013406 sec
loaded mesh in 0.006358 sec

In [4]:
vol_dict['R1-1'], type(vol_dict['R1-1'])

(7.97198675285296e-05, float)

In [5]:
area_dict['R1-1'], type(area_dict['R1-1'])

(0.009268815238064741, float)

read scalebarlist.csv to get the time-series order

In [6]:
sbl = pd.read_csv('scalebarlist.csv', header=None)
sbl

          0              1  2  3   4
0      R1-1   scalebar.csv  1  1   1
1      R1-2   scalebar.csv  1  1   2
2      R1-3   scalebar.csv  1  1   3
3      R1-4   scalebar.csv  1  1   4
4      R1-5   scalebar.csv  1  1   5
..      ...            ... .. ..  ..
336   5R3-6  scalebar2.csv  5  3   6
337   5R3-7  scalebar2.csv  5  3   7
338   5R3-8  scalebar2.csv  5  3   8
339   5R3-9  scalebar2.csv  5  3   9
340  5R3-10  scalebar2.csv  5  3  10

[341 rows x 5 columns]

In [7]:
area_volume_csv = pd.DataFrame(columns=[['label', 'group_id', 'bucket_id', 'pin_id', 'area (cm2)', 'volume (cm3)']])

for i, label in enumerate(sbl[0]):
    vol_cm = vol_dict[label] * 1000 * 1000
    area_cm = area_dict[label] * 100 * 100

    if vol_cm == 0:
        print(f"{label} has 0 volume")

    if area_cm == 0:
        print(f"{label} has 0 area")

    area_volume_csv.loc[len(area_volume_csv),:] = [label, sbl.loc[i, 2], sbl.loc[i, 3], sbl.loc[i, 4], area_cm, vol_cm]

In [8]:
area_volume_csv

      label group_id bucket_id pin_id  area (cm2) volume (cm3)
0      R1-1        1         1      1   92.688152    79.719868
1      R1-2        1         1      2  188.680629    216.66425
2      R1-3        1         1      3   139.38554   142.948028
3      R1-4        1         1      4   99.121849    89.372959
4      R1-5        1         1      5   54.382122    36.550285
..      ...      ...       ...    ...         ...          ...
336   5R3-6        5         3      6   95.020869    79.426222
337   5R3-7        5         3      7   71.473405    51.327648
338   5R3-8        5         3      8  112.212137    95.468087
339   5R3-9        5         3      9  162.180051   175.928857
340  5R3-10        5         3     10  130.446836   128.956897

[341 rows x 6 columns]

In [ ]:
area_volume_csv.to_csv(os.path.join(cfg.working_directory, "outputs", "mesh_area_volume.csv"), index=None)